[package]
name = "bootsim"
version = "0.1.0"
authors = ["David Brown <davidb@davidb.org>"]

[features]
default = []

sig-rsa = ["mcuboot-sys/sig-rsa"]

[build-dependencies]
gcc = "0.3.38"

[dependencies]
libc = "0.2.0"
rand = "0.3.0"
docopt = "0.8"
serde = "1.0"
serde_derive = "1.0"
log = "0.3"
env_logger = "0.4"
simflash = { path = "simflash" }
mcuboot-sys = { path = "mcuboot-sys" }
ring = { version = "0.11", features = ["rsa_signing"] }
untrusted = "0.5"
pem = "0.4"

[profile.test]
opt-level = 1
